### ISSUE TITLE
Unable to add an IPD patient, shows as 'duplicate entry'.

### ISSUE THREAD

**Issue by nikhilbalwani** [hetjagani/Hospital-Management-System#4]
Inputs and outputs for this bug can be found below:

![Screenshot from 2019-05-06 12-38-32](https://user-images.githubusercontent.com/31470608/57210980-53ce9500-6ffc-11e9-8401-34c15775645c.png)
![Screenshot from 2019-05-06 12-38-37](https://user-images.githubusercontent.com/31470608/57210983-54672b80-6ffc-11e9-963a-cca1439483f8.png)

**Comment by hetjagani** [comment]
Write date in dd/mm/yyyy manner. Use the browser's date select feature. It would work. Also update your database if not done as latest commit.
