### ISSUE TITLE
Unable to give prescriptions 

### ISSUE THREAD

**Issue by sphindocha** [hetjagani/Hospital-Management-System#5]
![Screenshot (48)](https://user-images.githubusercontent.com/50264574/57211568-927d3480-6f95-11e9-8876-554d6cc3421e.png)
![Screenshot (49)](https://user-images.githubusercontent.com/50264574/57211569-927d3480-6f95-11e9-9278-ca4abde7ff36.png)

**Comment by hetjagani** [comment]
This is working properly. In your case you might have opened the give_prescription.php page directly. Please do not do that. First Login then only all the functionality would work. It would need authentication.
