### ISSUE TITLE
Head Doctor Menu View

### ISSUE THREAD

**Issue by krupali2705** [hetjagani/Hospital-Management-System#6]
Head Doctor Menu shows stretched buttons.
![1212](https://user-images.githubusercontent.com/50312754/57226913-b0967380-702d-11e9-9304-4a3cffb93638.png)

**Comment by parshwa1999** [comment]
Solved

![qqq](https://user-images.githubusercontent.com/24487985/57227293-a6c14000-702e-11e9-8cc3-5a9ced3324ac.png)
